#!/bin/bash

OLDNAME=""
NEW_COMMITER_NAME=""
NEW_AUTHOR_NAME=""
NEW_COMMITTER_EMAIL=""
NEW_AUTHOR_EMAIL=""

git filter-branch --commit-filter "
        if [ \"\$GIT_COMMITTER_NAME\" = \"${OLDNAME}\" ];
        then
                GIT_COMMITTER_NAME=\"${NEW_COMMITER_NAME}\";
                GIT_AUTHOR_NAME=\"${NEW_AUTHOR_NAME}\";
                GIT_COMMITTER_EMAIL=\"${NEW_COMMITTER_EMAIL}\";
                GIT_AUTHOR_EMAIL=\"${NEW_AUTHOR_EMAIL}\";
                git commit-tree \"\$@\";
        else
                git commit-tree \"\$@\";
        fi" HEAD
